### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by walksanatora** [mgit-at/typescript-flatbuffers-codegen#2]
hello I am using this since Flatbuffers dont generate a object API (using flatbuffers 2.0.0) even with the --gen-object-api flag
but whenever I run it it errors out at me saying 
```
/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/@mgit-at/typescript-flatbuffers-codegen/dist/bin/flattsc.js:26
var execa = __importStar(require("execa"));
                         ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/execa/index.js from /home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/@mgit-at/typescript-flatbuffers-codegen/dist/bin/flattsc.js not supported.
Instead change the require of index.js in /home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/@mgit-at/typescript-flatbuffers-codegen/dist/bin/flattsc.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/walksanator/.nvm/versions/node/v16.10.0/lib/node_modules/@mgit-at/typescript-flatbuffers-codegen/dist/bin/flattsc.js:26:26) {
  code: 'ERR_REQUIRE_ESM'
}
```
any help is apprecieted

**Comment by aveexy** [comment]
This is because the execa devs changed the package to be ESM only. 
You can read about this change here: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c 

The actual problem here is that I somehow have forgotten to include the execa dependency in  package.json.
At the time I built this package execa 4.0.0 was the newest version. 

I released a new version that now includes the right execa version as a dependency.
